apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: vk
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Hello Kubernetes</title>
        <style>
            body, html {
                height: 100%;
                margin: 0;
                display: flex;
                justify-content: center;
                align-items: center;
                font-family: Arial, sans-serif;
            }
        </style>
    </head>
    <body>
        <h1>Hello, Kubernetes!</h1>
    </body>
    </html>

