apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: vk
data:
  index.html: |
    <html>
      <head>
        <title>Hello Kubernetes</title>
      </head>
      <body>
        <h1>Hello, Kubernetes!</h1>
      </body>
    </html>

